export default [
  {
    id: '1',
    type: 'processNode',
    sourcePosition: 'right',
    targetPosition: 'left',
    selected: false,
    data: {
      processName: '',
      people: 0,
      processTime: 0,
      waitTime: 0,
      pctCompleteAccurate: 100,
    },
    style: {
      width: 220,
      background: '#fff',
      borderColor: 'rgb(37, 50, 77)',
      borderRadius: '12px',
      borderStyle: 'solid',
      borderWidth: '4px',
      padding: 5,
    },
    position: { x: 100, y: 100 },
  },
  {
    id: '2',
    type: 'processNode',
    sourcePosition: 'right',
    targetPosition: 'left',
    selected: false,
    data: {
      processName: '',
      people: 0,
      processTime: 0,
      waitTime: 0,
      pctCompleteAccurate: 100,
    },
    style: {
      width: 220,
      background: '#fff',
      borderColor: 'rgb(37, 50, 77)',
      borderRadius: '12px',
      borderStyle: 'solid',
      borderWidth: '4px',
      padding: 5,
    },
    position: { x: 380.00003644963357, y: 150 },
  },
  {
    id: 'baeb2b43-8287-457b-9e16-a1c4add0eee2',
    source: '1',
    target: '2',
    arrowHeadType: 'arrowclosed',
    type: 'custom',
    selected: false,
  },
]
