export default [
  { id: 1, name: 'Mandalore' },
  { id: 2, name: 'Mon Cala' },
  { id: 3, name: 'Moraband' },
  { id: 4, name: 'Mortis' },
  { id: 5, name: 'Mustafar' },
  { id: 6, name: 'Mygeeto' },
  { id: 7, name: 'Naboo' },
  { id: 8, name: 'Nal Hutta' },
  { id: 9, name: 'Nevarro' },
  { id: 10, name: 'Numidian Prime' },
  { id: 11, name: 'Onderon' },
  { id: 12, name: 'Ord Mantell' },
  { id: 13, name: 'Pasaana' },
  { id: 14, name: 'Pillio' },
  { id: 15, name: 'Polis Massa' },
  { id: 16, name: 'Rishi' },
  { id: 17, name: 'Rodia' },
  { id: 18, name: 'Rugosa' },
  { id: 19, name: 'Ruusan' },
  { id: 20, name: 'Ryloth' },
  { id: 21, name: 'Saleucami' },
  { id: 22, name: 'Savareen' },
  { id: 23, name: 'Scarif' },
  { id: 24, name: 'Serenno' },
  { id: 25, name: 'Shili' },
  { id: 26, name: 'Sissubo' },
  { id: 27, name: 'Skako Minor' },
  { id: 28, name: 'Sorgan' },
  { id: 29, name: 'Starkiller Base' },
  { id: 30, name: 'Subterrel' },
  { id: 31, name: 'Sullust' },
  { id: 32, name: 'Takodana' },
  { id: 33, name: 'Tatooine' },
  { id: 34, name: 'Teth' },
  { id: 35, name: 'Toydaria' },
  { id: 36, name: 'Trandosha' },
  { id: 37, name: 'Umbara' },
  { id: 38, name: 'Utapau' },
  { id: 39, name: 'Vardos' },
  { id: 40, name: 'Wobani' },
  { id: 41, name: 'Wrea' },
  { id: 42, name: 'Yavin 4' },
  { id: 43, name: 'Zeffo' },
  { id: 44, name: 'Zygerria' },
]
