export default [
  { id: 1, productGroup: 'Party Bus', name: 'Mandalore' },
  { id: 2, productGroup: 'Big Bang', name: 'Mon Cala' },
  { id: 3, productGroup: 'Iron Bank', name: 'Moraband' },
  { id: 4, productGroup: 'Party Bus', name: 'Mortis' },
  { id: 5, productGroup: 'Big Bang', name: 'Mustafar' },
  { id: 6, productGroup: 'Iron Bank', name: 'Mygeeto' },
  { id: 7, productGroup: 'Party Bus', name: 'Naboo' },
  { id: 8, productGroup: 'Big Bang', name: 'Nal Hutta' },
  { id: 9, productGroup: 'Iron Bank', name: 'Nevarro' },
  { id: 10, productGroup: 'Party Bus', name: 'Numidian Prime' },
  { id: 11, productGroup: 'Big Bang', name: 'Onderon' },
  { id: 12, productGroup: 'Iron Bank', name: 'Ord Mantell' },
  { id: 13, productGroup: 'Party Bus', name: 'Pasaana' },
  { id: 14, productGroup: 'Big Bang', name: 'Pillio' },
  { id: 15, productGroup: 'Iron Bank', name: 'Polis Massa' },
  { id: 16, productGroup: 'Party Bus', name: 'Rishi' },
  { id: 17, productGroup: 'Big Bang', name: 'Rodia' },
  { id: 18, productGroup: 'Iron Bank', name: 'Rugosa' },
  { id: 19, productGroup: 'Party Bus', name: 'Ruusan' },
  { id: 20, productGroup: 'Big Bang', name: 'Ryloth' },
  { id: 21, productGroup: 'Iron Bank', name: 'Saleucami' },
  { id: 22, productGroup: 'Party Bus', name: 'Savareen' },
  { id: 23, productGroup: 'Big Bang', name: 'Scarif' },
  { id: 24, productGroup: 'Iron Bank', name: 'Serenno' },
  { id: 25, productGroup: 'Party Bus', name: 'Shili' },
  { id: 26, productGroup: 'Big Bang', name: 'Sissubo' },
  { id: 27, productGroup: 'Iron Bank', name: 'Skako Minor' },
  { id: 28, productGroup: 'Party Bus', name: 'Sorgan' },
  { id: 29, productGroup: 'Big Bang', name: 'Starkiller Base' },
  { id: 30, productGroup: 'Iron Bank', name: 'Subterrel' },
  { id: 31, productGroup: 'Party Bus', name: 'Sullust' },
  { id: 32, productGroup: 'Big Bang', name: 'Takodana' },
  { id: 33, productGroup: 'Iron Bank', name: 'Tatooine' },
  { id: 34, productGroup: 'Party Bus', name: 'Teth' },
  { id: 35, productGroup: 'Big Bang', name: 'Toydaria' },
  { id: 36, productGroup: 'Iron Bank', name: 'Trandosha' },
  { id: 37, productGroup: 'Party Bus', name: 'Umbara' },
  { id: 38, productGroup: 'Big Bang', name: 'Utapau' },
  { id: 39, productGroup: 'Iron Bank', name: 'Vardos' },
  { id: 40, productGroup: 'Party Bus', name: 'Wobani' },
  { id: 41, productGroup: 'Big Bang', name: 'Wrea' },
  { id: 42, productGroup: 'Iron Bank', name: 'Yavin 4' },
  { id: 43, productGroup: 'Party Bus', name: 'Zeffo' },
  { id: 44, productGroup: 'Big Bang', name: 'Zygerria' },
]
